apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt-certs
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: acm-lab-config
  source:
    path: manifests/letsencrypt-certs/base
    repoURL: https://github.com/ocp-tigers/acm-lab-deploy
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  sync:
    comparedTo:
      destination:
        namespace: openshift-gitops
        server: https://kubernetes.default.svc
      source:
        path: manifests/letsencrypt-certs/base
        repoURL: https://github.com/ocp-tigers/acm-lab-deploy
        targetRevision: master
